### ISSUE TITLE
How to initialize chunks {x1,x2,...,xn} ?

### ISSUE THREAD

**Issue by RewindL** [thunlp/LLMxMapReduce#2]
Compressions {c1, c2,..., cK} come from original text chunks {x1,x2,...,xn}, but how does LLMxMapReduce split long text to these chunks ? Equal length division or based on periods ？

**Comment by hansjohn** [comment]
We first perform an initial split of the long text based on newline characters (`\n`), dividing the text into multiple paragraphs. Then, these fragments are sequentially concatenated into a chunk until the chunk's length approaches the predefined `chunk_size` limit.

During this concatenation process, if a particular fragment exceeds the `chunk_size` limit, we further split that content based on sentence boundaries. Then, we proceed to fill the chunk following the same rules mentioned above, ensuring each chunk respects both the size limit and the preservation of meaningful sentence boundaries.

**Comment by RewindL** [comment]
> boundaries

Got it. Thanks for replying :-)
